env: production
image: uffizzicloud/uffizzi-app
web-replicas: 3
sidekiq-replicas: 1
hostname: localhost
controller_url: http://localhost:8080
allowed_hosts: "*"
db_host: localhost
db_port: 5432
db_user: uffizzi-user
db_name: uffizzi
db_password: ChangeMeNow
rails_secret_key_base: ChangeMeNow
redis_url: localhost
basic_auth_login: username
basic_auth_password: ChangeMeNow
controller_basic_auth_login: username
controller_basic_auth_password: password
github_app_id: ChangeMeNow
github_app_slug: ChangeMeNow
github_client_id: ChangeMeNow
github_client_secret: ChangeMeNow
github_private_key: ChangeMeNow
github_webhook_secret: ChangeMeNow
sql_credentials_secret_name: example
feature_mailchimp: false
feature_email_delivery: false
feature_google_maps: false
feature_sentry: false
feature_stripe: false
